store:
  # https://github.com/verdaccio/verdaccio/tree/master/packages/plugins/aws-storage
  aws-s3-storage:
    bucket: verdaccio-ekshin
    keyPrefix: gracefullight
    region: ap-northeast-2
    # endpoint: https://{service}.{region}.amazonaws.com # optional, will use aws s3's default behavior if not specified
    # s3ForcePathStyle: false # optional, will use path style URLs for S3 objects
    # sessionToken: your-session-token # optional, aws sessionToken for private S3 bucket

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  "@gracefullight/*":
    access: $all
    publish: $authenticated
    storage: "scoped"
  "**":
    access: $all
    publish: $authenticated
    proxy: npmjs
    storage: "public"

# max_body_size: 10mb

# notify:
#   method: POST
#   headers: [{ "Content-Type": "application/json" }]
#   endpoint: https://usagge.hipchat.com/v2/room/3729485/notification?auth_token=mySecretToken
#   content: '{"color":"green","message":"New package published: * {{ name }}*","notify":true,"message_format":"text"}'

middlewares:
  audit:
    enabled: true


web:
  enable: true
  title: Gracefullight
  # logo: http://somedomain/somelogo.png
  primary_color: "#4b5e40"
  gravatar: true
  # scope: "@scope"
  # sort_packages: asc | desc
  darkMode: true
  # favicon: http://somedomain/favicon.ico | /path/favicon.ico
  pkgManagers:
    - npm
    - yarn

logs: { type: stdout, format: pretty-timestamped, level: http }
